### ISSUE TITLE
Убрать из сервиса Activity

### ISSUE THREAD

**Issue by LionZXY** [madsunrise/Mobilization#1]
При смерти Activity у тебя в сервисе остается ссылка на Activity (CallBack). Используй ResultReciver или Broadcast для передачи информации в Activity

**Comment by LionZXY** [comment]
Костыль:
``` 
@Override
protected void onDestroy() {
        super.onDestroy();
        translatorService.setCallback(null);
}
```
Ссылка на Activity, вообще, никогда и не при каких обстоятельствах не должна оказываться в Background-потоке

**Comment by madsunrise** [comment]
Привет. Я наоборот слышал, что Broadcast или ResultReceiver в боевых проектах НЕ используются. И то же самое вам будут говорить на 3-ем семестре.

**Comment by LionZXY** [comment]
Где слышал? Ну тот вариант, который тут, вообще, не вариант
P.S. Написал в ЛС преподу по Android. Жду ответа

**Comment by madsunrise** [comment]
Давай, отпиши потом. Мне нравится управлять многопоточностью через Executors, не вижу в этом ничего плохого.
P.S. Актуальный код в ветке develop

**Comment by LionZXY** [comment]
А ну эт, естественно, что в develop. Ну нравиться, это не значит хорошо. В Android лучше все привязывать к жизненному циклу. Я обычно делаю Service и потоки по ресурсам, и таски.

**Comment by madsunrise** [comment]
Что ответил преподаватель?

**Comment by LionZXY** [comment]
Ничего 
![image](https://cloud.githubusercontent.com/assets/5871715/25349418/6ffb7f10-292a-11e7-9543-789ac546c207.png)

**Comment by madsunrise** [comment]
Окей, на портале он долго отвечает, да. Ну подождем.

**Comment by LionZXY** [comment]
Понял. Хотя как-то странно. А у тебя какой-то опыт работы есть? Или откуда ты всю эту инфу получил? Записи технопарка?
![image](https://cloud.githubusercontent.com/assets/5871715/25377181/7c9ead84-29af-11e7-8694-6ee8de59b37b.png)

**Comment by madsunrise** [comment]
Опыта нет, на лекции ходил

**Comment by LionZXY** [comment]
Ходил? Просто взял и приходил?) Технопарка?

**Comment by madsunrise** [comment]
Ну я вообще студент Технопарка, это удивительно?)

**Comment by LionZXY** [comment]
Думал ты < 3 семестр :)
Ну ок. Пойду смотреть лекции. Смотрел записи мобилизации прошлой, там, в основном, Best Practices. И да. По факту, эксекутор + колбеки тоже самое, что ResultReciever (Handler + колбек)

**Comment by madsunrise** [comment]
Кто бы спорил...
